Book title
scieloorg/scielo_scholarly_data pull request #39
Opened 2022-01-15 18:58 UTC by Rossi-Luciano

### O que esse PR faz?
Adiciona métodos de padronização de títulos de livros, especificamente para a visualização e deduplicação de títulos.

### Onde a revisão poderia começar?
Há três _commits_, para os métodos, para os testes automatizados e para a atualização do README. A revisão pode seguir por este caminho.

### Como este poderia ser testado manualmente?
NA.

### Algum cenário de contexto que queira dar?
As decisões sobre as manipulações aplicadas seguiram de acordo com as padronizações anteriores.

### Screenshots
NA.

### Quais são tickets relevantes?
NA.

### Referências
NA.

2022-01-19 16:01 UTC, rafaelpezzuto requested changes
@Rossi-Luciano Fiz algumas observações que precisam ser corrigidas.

2022-01-19 16:01 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +    return text
@Rossi-Luciano Veja issue #43 para tentar contemplar também neste método o que descrevo lá. É importante ser capaz de receber uma lista de caracteres que precisam ser removidos do texto (uma espécie de lista de remoção - de caracteres e não de palavras como existe para journal_title_for_deduplication).

2022-01-22 12:50 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +    remove_char : bool, default True
O nome do parâmetro foi alterado, conforme sugerido.

2022-01-22 12:51 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +    if remove_special_char:
O nome do parâmetro foi alterado, conforme sugerido.

2022-01-22 14:26 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +    return text
Sugestão implementada, porém ficou uma dúvida aqui quanto a utilizar uma lista de caracteres genérica, que pode ser utilizada por diferentes métodos, ou uma lista específica para cada método. Optei, por hora, por uma lista específica.

2022-01-22 14:27 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +    if remove_special_char:
O parâmetro foi renomeado.

2022-01-27 15:52 UTC, rafaelpezzuto requested changes
@Rossi-Luciano Fiz mais algumas sugestões.

2022-01-27 15:52 UTC, rafaelpezzuto commented on scielo_scholarly_data/core.py
> +def remove_specific_chars_from_list(text, chars_to_remove):
@Rossi-Luciano Sugiro que o método se chame `remove_chars`, apenas.

2022-01-27 15:52 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +def journal_title_for_deduplication(text: str, words_to_remove=JOURNAL_TITLE_SPECIAL_WORDS,
@Rossi-Luciano Assim como existe o `words_to_remove`, sugiro que exista o `chars_to_remove` (uma lista). Assim, bastaria iterar na lista para remover os caracteres.

Por padrão, chars_to_remove seria uma lista vazia:

`def journal_title_for_deduplication(text: str, words_to_remove=JOURNAL_TITLE_SPECIAL_WORDS, keep_parenthesis_content=True, chars_to_remove=[])`

2022-01-27 15:52 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +    if remove_specific_chars:
Sendo `chars_to_remove` uma lista, bastaria fazer:

`text = remove_chars(text, chars_to_remove)`

2022-01-27 15:52 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +def document_author_for_deduplication(text: str, surname_first=True, remove_specific_chars=False):
@Rossi-Luciano Aplicar as mesmas sugestões feitas para o método `...for_visualization`.

2022-01-27 15:52 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +def book_title_for_deduplication(text: str, keep_alpha_num_space_chars_only=True, remove_specific_chars=False):
@Rossi-Luciano Aplicar as mesmas sugestões feitas para o método `...for_visualization`.

2022-01-27 15:52 UTC, rafaelpezzuto commented on scielo_scholarly_data/values.py
> +CHARS_TO_REMOVE_IN_DOCUMENT_AUTHORS = {
@Rossi-Luciano Acredito que não precisamos destes quatro dicionários

2022-01-28 22:47 UTC, Rossi-Luciano commented on scielo_scholarly_data/core.py
> +def remove_specific_chars_from_list(text, chars_to_remove):
Feito.

2022-01-28 22:47 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +def journal_title_for_deduplication(text: str, words_to_remove=JOURNAL_TITLE_SPECIAL_WORDS,
Feito.

2022-01-28 22:48 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +    if remove_specific_chars:
Feito.

2022-01-28 22:48 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +def document_author_for_deduplication(text: str, surname_first=True, remove_specific_chars=False):
Feito.

2022-01-28 22:48 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +def book_title_for_deduplication(text: str, keep_alpha_num_space_chars_only=True, remove_specific_chars=False):
Feito.

2022-01-28 22:48 UTC, Rossi-Luciano commented on scielo_scholarly_data/values.py
> +CHARS_TO_REMOVE_IN_DOCUMENT_AUTHORS = {
OK.

2022-01-30 22:42 UTC, rafaelpezzuto approved these changes

2022-01-30 22:42 UTC, merged