Book editor name
scieloorg/scielo_scholarly_data pull request #41
Opened 2022-01-15 20:00 UTC by Rossi-Luciano

### O que esse PR faz?
Adiciona os métodos de padronização de nomes de editores de livros, para visualização e deduplicação.
Estes métodos são os mesmos utilizados para a padronização de nomes de autores de documentos, é preciso verificar a viabilidade de mantê-los independentes ou de unificá-los para padronização de nomes de pessoas.

### Onde a revisão poderia começar?
Há quatro _commits_, para os métodos, para os testes automatizados, para a generalização do _set_ de pontuação e para a atualização do README. A revisão pode seguir este caminho.

### Como este poderia ser testado manualmente?
NA.

### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

### Quais são tickets relevantes?
NA.

### Referências
NA.

2022-01-19 16:34 UTC, rafaelpezzuto requested changes
Os tratamentos relacionados a `editor name` na verdade são para `publisher`. Ou seja, estamos interessados em tratar nomes de Editoras (casas publicadoras) e não nomes de pessoas que exercem o papel de editor ou editora. Segue uma lista de nomes de editoras com os respectivos acrônimos/siglas:

```
FIOCRUZ | Editora FIOCRUZ
Editora da Universidade Federal da Bahia | EDUFBA
Editora da Universidade Estadual de São Paulo | Editora UNESP
Editora da Universidade Estadual da Paraíba | EDUEPB
Editora da Universidade Federal de São Carlos | EdUFSCar
Editora da UEM | EDUEM
EDUERJ | EDUERJ
Editus - Editora da UESC | Editus - Editora da UESC
Editorial Universidad del Rosario | Editorial UR
Editora da UFRGS | Editora da UFRGS
Editora UFABC | Editora UFABC
Editora da Unicamp | Editora Unicamp
Editora UFMG | Editora UFMG
Editorial Universidad Autónoma de Occidente | Editorial UAO
Editora da Universidade Federal de Uberlândia | EDUFU
Editora da Universidade Federal da Fronteira Sul | Editora UFFS
Editora Universidade de Brasília | Editora UnB
Editora da Universidade do Estado da Bahia | EDUNEB
Editorial Abya-Yala | Editorial Abya-Yala
```

O site SciELO Livros contém alguns dados que podem ser interessantes: https://books.scielo.org

2022-01-22 19:25 UTC, Rossi-Luciano commented
Os métodos `book_editor_name_for_visualization` e `book_editor_name_for_deduplication` foram corrigidos conforme os esclarecimentos.
Notem que os procedimentos aplicados seguem de acordo com os demais considerados para outros procedimentos de **padronização**. Acredito (não tenho certeza) que procedimentos mais sofisticados serão adicionado no módulo de deduplicação, caso não seja assim me avisem que providenciarei.

2022-01-27 15:54 UTC, rafaelpezzuto requested changes
@Rossi-Luciano Fiz apenas uma sugestão.

2022-01-27 15:54 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +def book_editor_name_for_visualization(text: str, remove_special_char=True):
O nome correto do parâmetro é 

`keep_alpha_num_space_only`

2022-01-30 22:43 UTC, rafaelpezzuto approved these changes

2022-01-30 22:48 UTC, merged