Orcid validator
scieloorg/scielo_scholarly_data pull request #42
Opened 2022-01-16 14:16 UTC by Rossi-Luciano

### O que esse PR faz?
Adiciona método para a validação de um registro ORCID.

### Onde a revisão poderia começar?
Por _commit_

### Como este poderia ser testado manualmente?
NA.

### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

### Quais são tickets relevantes?
#40 

### Referências
[support.orcid.org](https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier)

2022-01-18 20:51 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +        type : int
@Rossi-Luciano acredito que este parâmetro pode ser mais específico. Aliás, podemos ter mais de um parâmetro para indicar o que queremos fazer.

Sugiro: 

1. Mudar `type` para `exec_mode` ou `mode`;
2. Usar biblioteca urllib.parse para fazer o parse de um endereço uri (veja exemplos [aqui](https://docs.python.org/3/library/urllib.parse.html);
3. Ao usar o parse indicado em 2, será possível extrair o `host` e o `path` - é melhor extraí-los, quando possível;
4. O `path` seria o alvo da validação na situação em que a opção escolhida pelo usuário for verificar o check-sum;
5. Na situação em que não é informado o enderço completo do orcid (sem http e host), e o usuário escolher validar, o conteúdo informado é que deve ser validado;
6. Deve haver um parâmetro que a pessoa indica para apenas validar o formato (e não o checksum);

2022-01-18 20:56 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +        type : int
@Rossi-Luciano aqui há exemplo de como usei o urllib.parse: https://github.com/scieloorg/scielo_usage_counter/blob/d1093d088813e90863adfd31b747c781b10088e5/app/lib/logparser.py#L374

Veja o que há dentro de um objeto retornado pela função `urllib.parse.urlparse(path)`. Basicamente há um host, um protocolo, um path e parâmetros de url, se houver.

2022-01-19 15:54 UTC, rafaelpezzuto commented
@Rossi-Luciano Fiz alguns comentários. Quando puder, avalie-os (e se for o caso, agendemos uma conversa).

2022-01-25 21:30 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +def orcid_validator(text: str, type=1):
A assinatura deverá dois parâmetros:
`text`
`return_mode: host, path, uri`

Havendo problema de validação, o retorno será um dicionário com os erros:

{"error": "invalid format"}

ou

{"error": "invalid checksum"}

2022-01-27 16:19 UTC, rafaelpezzuto requested changes
@Rossi-Luciano Fiz algumas sugestões.

2022-01-27 16:19 UTC, rafaelpezzuto commented on scielo_scholarly_data/standardizer.py
> +    if not re.match(PATTERN_ORCID, orcid.path):
E portanto, a linha seguinte ficaria:

```
if not matched_orcid:
    return {'error': 'invalid format'}
```
E as seguintes também poderiam usar a variável `matched_orcid`:

``` 
path = keep_alpha_num_space(matched_orcid.groups()[1]), replace_with='')
```

E as linhas 502 e 504 também.

2022-01-28 23:17 UTC, Rossi-Luciano commented on scielo_scholarly_data/values.py
> +PATTERN_ORCID = r'(\S*)(\d{4}-\d{4}-\d{4}-\d{3}[\d|X])(\S*)'
Ok

2022-01-28 23:20 UTC, Rossi-Luciano commented on scielo_scholarly_data/standardizer.py
> +    if not re.match(PATTERN_ORCID, orcid.path):
Feito.

2022-01-30 22:54 UTC, rafaelpezzuto approved these changes

2022-01-30 22:58 UTC, merged