Volume numerico
scieloorg/scielo_scholarly_data pull request #57
Opened 2022-05-04 19:18 UTC by Rossi-Luciano

### O que esse PR faz?
Adiciona a funcionalidade de remoção de caracteres alfabéticos em identificadores de volume.

### Onde a revisão poderia começar?
Por _commits_

### Como este poderia ser testado manualmente?
NA.

### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

### Quais são tickets relevantes?
#54 

### Referências
NA.

2022-05-04 22:19 UTC, rafaelpezzuto requested changes
@Rossi-Luciano

Do modo como está implementado, faz bastante sentido para os métodos que uso para bibliometria. Esses métodos sempre precisam de volume em termos de número (isto é, sem letras). Porém, pode haver situações em que não se deseja forçar o volume para algo numérico (quando uma letra acompanha o volume: 63a, 63b, etc..)

Sugiro então que haja uma variável de controle chamada `force_integer` que é setada como True por padrão. Ficaria assim:

```
if not digit_only:
    return text

result = []
for char in text:
    if char.isnumeric():
        result.append(char)
``` 

Ainda há as questões de volume em números romanos. Já tenho uma ideia de como resolver, mas primeiro vamos fechar este PR.

2022-05-06 19:12 UTC, Rossi-Luciano commented
Foram incluídos argumentos para as opções de manter somente números e para a conversão de romano para indo-arábico.
Atende, também, a issue #53.

2022-05-11 18:49 UTC, rafaelpezzuto requested changes
@Rossi-Luciano 

Tentei rodar os testes automáticos e ocorreram dois erros. Um está relacionado a falta de import do roman_to_int e de int_to_roman. Depois de fazer esse import corretamente, ainda ocorreram erros. Desta vez, relacionados à conversão em si. Veja as duas saídas (primeiro o erro de import e depois o erro de conversão).

PS: sugiro que use a biblioteca `roman` que eu havia mencionado. Ela já trata erros (e gera um Error que eu gostaria de capturar na outra aplicação que irá usar o scholarly_data).

```bash
======================================================================
ERROR: test_int_to_roman (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/tests/test_core.py", line 207, in test_int_to_roman
    obtained_values = [str(int_to_roman(romans)) for romans in nums]
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/tests/test_core.py", line 207, in <listcomp>
    obtained_values = [str(int_to_roman(romans)) for romans in nums]
NameError: name 'int_to_roman' is not defined

======================================================================
ERROR: test_roman_to_int (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/tests/test_core.py", line 195, in test_roman_to_int
    obtained_values = [str(roman_to_int(ints)) for ints in nums]
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/tests/test_core.py", line 195, in <listcomp>
    obtained_values = [str(roman_to_int(ints)) for ints in nums]
NameError: name 'roman_to_int' is not defined

----------------------------------------------------------------------
Ran 144 tests in 0.009s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=144 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=144 errors=2 failures=0>
```


```bash
======================================================================
ERROR: test_int_to_roman (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/tests/test_core.py", line 209, in test_int_to_roman
    obtained_values = [str(int_to_roman(romans)) for romans in nums]
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/tests/test_core.py", line 209, in <listcomp>
    obtained_values = [str(int_to_roman(romans)) for romans in nums]
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/scielo_scholarly_data/core.py", line 420, in int_to_roman
    if not type(integer) == int and not 0 < integer < 4000:
TypeError: '<' not supported between instances of 'int' and 'str'

======================================================================
FAIL: test_roman_to_int (tests.test_core.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/tests/test_core.py", line 199, in test_roman_to_int
    self.assertListEqual(expected_values, obtained_values)
AssertionError: Lists differ: ['20', '1922', '2022', '1554'] != ['20', '1922', '2022', '1604']

First differing element 3:
'1554'
'1604'

- ['20', '1922', '2022', '1554']
?                          ^^

+ ['20', '1922', '2022', '1604']
?                          ^^


----------------------------------------------------------------------
Ran 144 tests in 0.009s

FAILED (failures=1, errors=1)
Test failed: <unittest.runner.TextTestResult run=144 errors=1 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=144 errors=1 failures=1>
```

2022-05-16 16:41 UTC, rafaelpezzuto commented
Fechado pois foi tratado no PR #58.

2022-05-16 16:41 UTC, closed without merging