Date new
scieloorg/scielo_scholarly_data pull request #59
Opened 2022-05-16 20:02 UTC by Rossi-Luciano

### O que esse PR faz?
Adiciona procedimento para o tratamento de datas (substituirá o anterior).

### Onde a revisão poderia começar?
Por _commits_

### Como este poderia ser testado manualmente?
NA.

### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

### Quais são tickets relevantes?
NA.

### Referências
NA.

2022-05-17 02:55 UTC, ednilson requested changes
@Rossi-Luciano precisa tratar as exceções. Acho que pode continuar com base nos testes que fizemos sempre retornando algo, como uma tupla ou dicionario. O importante é informar o resultado (texto normalizado/transformado (ou não)) e se houve exceção, informando qual.

2022-05-17 02:55 UTC, ednilson commented on scielo_scholarly_data/dates.py
> +import re
@Rossi-Luciano essas bibliotecas não estão sendo usadas.

2022-05-18 17:16 UTC, rafaelpezzuto reviewed
@Rossi-Luciano Fiz algumas observações e gostaria que a @robertatakenaka dessa uma olhada.

No mais, o principal método `convert_to_iso...` está muito mais claro!

2022-05-18 17:16 UTC, rafaelpezzuto commented on scielo_scholarly_data/dates.py
> +        return text[:4] + '-' + text[4:6] + '-' + text[6:]
É difícil saber que no meio do texto está o mês e no final o dia.

Porque não usamos aquele procedimento do "date util parser" que já tenta fazer isso por nós?

2022-05-18 17:16 UTC, rafaelpezzuto commented on scielo_scholarly_data/dates.py
> +        return text
O método assume algumas coisas com base no tamanho da string informada e na presença de preposições. Há alguma razão para não tentarmos fazer a padronização usando algo já pronto como o `date util parser`?

@robertatakenaka, não seria melhor fazer um fork do `dateutil.parser` (https://dateutil.readthedocs.io/en/stable/) e adicionar essas melhorias?

2022-05-18 17:16 UTC, rafaelpezzuto commented on scielo_scholarly_data/dates.py
> +        return MONTHS_DICT[month.lower()]
O nome do dicionário poderia ser mais explícito. Lendo `MONTHS_DICT` não sei o que é chave nem o que é valor. Eu costumo nomear dicionários usando o padrão `keyname_to_valuename` (às vezes fica comprido, mas facilita a leitura).

MONTHS_DICT seria algo como `text_month_to_numeric_month`

Não sei se @robertatakenaka concorda com isso.

2022-05-19 17:11 UTC, ednilson reviewed
OK

2022-05-20 14:46 UTC, Rossi-Luciano commented on scielo_scholarly_data/dates.py
> +        return MONTHS_DICT[month.lower()]
O nome do dicionário foi atualizado de acordo com a sugestão.

2022-05-20 15:25 UTC, ednilson commented on scielo_scholarly_data/dates.py
> +def convert_to_iso_date(text, day='01', month='01', only_year=False):
@Rossi-Luciano de acordo com a dica do @rafaelpezzuto e @robertatakenaka vamos usar `underscore` nos métodos auxiliares.

2022-05-20 15:25 UTC, ednilson commented on scielo_scholarly_data/dates.py
> +def split_date(text):
incluir _ no nome do método.
`def _split_date(text):`

2022-05-23 20:08 UTC, robertatakenaka commented on tests/test_dates.py
> +            dates.InvalidFormatError,
Use `InvalidDateValueError`

2022-06-07 00:57 UTC, ednilson commented on scielo_scholarly_data/dates.py
>  from dateutil.parser import parse
@Rossi-Luciano este import não está em uso

2022-06-07 00:57 UTC, ednilson commented on scielo_scholarly_data/dates.py
> +        y, m, d = text.split('-')
@rafaelpezzuto e @Rossi-Luciano entendi que esta é uma função 'interna' de uso exclusivo do módulo dates, que  quando chega neste ponto já é previsto que se trata de um 'mês'. Então ok.

2022-06-07 17:43 UTC, ednilson approved these changes

2022-06-07 17:44 UTC, ednilson approved these changes

2022-06-08 16:41 UTC, rafaelpezzuto requested changes
@Rossi-Luciano Olhei os commits, fiz a instalação e executei os testes.

Também fiz testes manuais simulando o uso da biblioteca. Observei que há um método `convert_to_iso_date` em `scielo_scholarly_data.standardizer` que age diferente do novo método que há em `scielo_scholarly_data.dates`. Acho que nós iremos manter apenas este último, certo?

Veja:
![image](https://user-images.githubusercontent.com/2096125/172670893-81dc3678-0855-4664-aab8-19aaa2ddb984.png)

2022-06-08 16:51 UTC, ednilson commented
@Rossi-Luciano seria melhor comparar os resultados obtidos do `dates.convert_to_iso_date ` com `standardizer.convert_to_iso_date` para garantir o melhor em dates. E depois poderia remover do `standardizer`

2022-06-10 14:32 UTC, rafaelpezzuto approved these changes
Remover convert_to_iso_date de `core` e substituir o método `core.convert_to_iso_date` por `dates.convert_to_iso_date` em standardizer.

2022-06-10 15:36 UTC, merged